This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240
program.cs(13,13): error CS0246: Не удалось найти имя типа или пространства имен "List" (пропущена директива using или ссылка на сборку?)
program.cs(13,92): error CS1061: "System.Array" не содержит определение для "ToList". Не удалось найти метод  расширения "ToList", принимающий первый аргумент типа "System.Array"  (пропущена директива using или ссылка на сборку?)